services:
  web:
    build: .
    container_name: renal_diet_web
    restart: unless-stopped
    ports:
      - "8000:8000" # Puerto 8000 (Proxy Nginx lo redirigirá al 80/443)
    volumes:
      - ./renal_diet.db:/app/renal_diet.db # BD persistente
      - ./images:/app/images # Imágenes persistentes
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env # Lee las variables desde el archivo .env si existe
